### ISSUE TITLE
File not found ''

### ISSUE THREAD

**Issue by DeDaKn** [ACG8/Mage-Wars-MSE-Template#8]
Hi,
I know this template goes waay back but I recently wanted to create custom cards and found it great that you took the time to create template for MSE.

There is an issue on my end where I get a File not found error:

![image](https://github.com/ACG8/Mage-Wars-MSE-Template/assets/121451418/11852844-4ea2-4887-b004-307f2d289e4f)

Looks to me that it's looking for a blank filename. I tried to find the issue myself but I wasn't able to.

Really the main issue is that I cannot properly choose the different elements of the cards. The dropdown simple disappears and I'm assuming it is because of that error.

After troubleshooting, I have a hunch that it has to do with the conjunction function but I may be wrong.

Hope I hear back from you

**Comment by ACG8** [comment]
It has been years since I did anything with MSE (I use NanDeck now, much better), but I think in this case I see the problem. Uploaded 0b8fb6a to fix; see if that works for you now.

**Comment by DeDaKn** [comment]
Works like a charm! Thank you very much!
